version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sportsline/api:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    secrets:
      - rsa_private
      - rsa_public

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-sportsline}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

secrets:
  rsa_private:
    file: ./secrets/rsa_private.pem
  rsa_public:
    file: ./secrets/rsa_public.pem

networks:
  backend:
    driver: bridge

volumes:
  pg_data:
